
package com.lvmama.vst.order.webservice.contract;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.1.4
 * Tue Dec 02 16:01:22 CST 2014
 * Generated source version: 2.1.4
 * 
 */
 
public class ContractWebService_ContractWebServicePort_Server{

    protected ContractWebService_ContractWebServicePort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ContractWebServiceImpl();
        String address = "http://test.contract-api.palmyou.com/ntsms-contract-api/service/ContractWebService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new ContractWebService_ContractWebServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
