
package com.lvmama.vst.order.webservice.contract;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import net.sf.json.JSONObject;

import com.lvmama.vst.comm.utils.MD5;

/**
 * This class was generated by Apache CXF 2.1.4
 * Tue Dec 02 16:01:22 CST 2014
 * Generated source version: 2.1.4
 * 
 */

public final class ContractWebServiceClient {

    private static final QName SERVICE_NAME = new QName("http://www.springframework.org/schema/beans", "ContractWebService");
    private static final ContractWSService wsService = new ContractWSService(ContractWSService.WSDL_LOCATION, SERVICE_NAME);
    
    private ContractWebServiceClient() {
    }

    public static String authentication(String code, String password) throws Exception {
    	ContractWebService port = wsService.getContractWebServicePort(); 
    	String returnStr = port.authentication(code, MD5.encode32(password));
//    	JSONObject jsonObj = JSONObject.fromObject(returnStr);
//    	ReturnContent returnContent = (ReturnContent)JSONObject.toBean(jsonObj, ReturnContent.class);
    	return returnStr;
    }
    
    public static String submitContract(String token, SubmitContractRequest submitContractRequest) throws Exception {
    	ContractWebService port = wsService.getContractWebServicePort(); 
    	String returnStr = port.submitContract(token, submitContractRequest);
//    	JSONObject jsonObj = JSONObject.fromObject(returnStr);
//    	ReturnContent returnContent = (ReturnContent)JSONObject.toBean(jsonObj, ReturnContent.class);
    	return returnStr;
    }
    
    public static String cancelContract(String token, CancelContractRequest cancelContractRequest) throws Exception {
    	ContractWebService port = wsService.getContractWebServicePort(); 
    	String returnStr = port.cancelContract(token, cancelContractRequest);
//    	JSONObject jsonObj = JSONObject.fromObject(returnStr);
//    	ReturnContent returnContent = (ReturnContent)JSONObject.toBean(jsonObj, ReturnContent.class);
    	return returnStr;
    }
    
    public static void main(String args[]) throws Exception {
    	authentication("l-sh-cj00056-a1", "1");
//        URL wsdlURL = ContractWSService.WSDL_LOCATION;
//        if (args.length > 0) { 
//            File wsdlFile = new File(args[0]);
//            try {
//                if (wsdlFile.exists()) {
//                    wsdlURL = wsdlFile.toURI().toURL();
//                } else {
//                    wsdlURL = new URL(args[0]);
//                }
//            } catch (MalformedURLException e) {
//                e.printStackTrace();
//            }
//        }
//      
//        ContractWSService ss = new ContractWSService(wsdlURL, SERVICE_NAME);
//        ContractWebService port = ss.getContractWebServicePort();  
        
//        {
//        System.out.println("Invoking complementGuest...");
//        java.lang.String _complementGuest_token = "";
//        com.lvmama.vst.order.webservice.contract.ComplementGuestRequest _complementGuest_complementGuestRequest = null;
//        java.lang.String _complementGuest__return = port.complementGuest(_complementGuest_token, _complementGuest_complementGuestRequest);
//        System.out.println("complementGuest.result=" + _complementGuest__return);
//
//
//        }
//        {
//        System.out.println("Invoking authentication...");
//        java.lang.String _authentication_code = "l-sh-cj00039-a";
//        java.lang.String _authentication_password = "1";
//        java.lang.String _authentication__return = port.authentication(_authentication_code, MD5.md5(_authentication_password));
//        System.out.println("password:" + MD5.md5(_authentication_password) + ", authentication.result=" + _authentication__return);
//

//        }
//        {
//        System.out.println("Invoking getMsgCode...");
//        java.lang.String _getMsgCode_token = "";
//        java.lang.String _getMsgCode_contractid = "";
//        java.lang.String _getMsgCode__return = port.getMsgCode(_getMsgCode_token, _getMsgCode_contractid);
//        System.out.println("getMsgCode.result=" + _getMsgCode__return);
//
//
//        }
//        {
//        System.out.println("Invoking submitContract...");
//        java.lang.String _submitContract_token = "";
//        com.lvmama.vst.order.webservice.contract.SubmitContractRequest _submitContract_submitContractRequest = null;
//        java.lang.String _submitContract__return = port.submitContract(_submitContract_token, _submitContract_submitContractRequest);
//        System.out.println("submitContract.result=" + _submitContract__return);
//
//
//        }
//        {
//        System.out.println("Invoking uploadContract...");
//        java.lang.String _uploadContract_token = "";
//        com.lvmama.vst.order.webservice.contract.SubmitContractRequest _uploadContract_submitContractRequest = null;
//        java.lang.String _uploadContract__return = port.uploadContract(_uploadContract_token, _uploadContract_submitContractRequest);
//        System.out.println("uploadContract.result=" + _uploadContract__return);
//
//
//        }
//        {
//        System.out.println("Invoking submitStatus...");
//        java.lang.String _submitStatus_token = "";
//        com.lvmama.vst.order.webservice.contract.SubmitStatusRequest _submitStatus_submitStatusRequest = null;
//        java.lang.String _submitStatus__return = port.submitStatus(_submitStatus_token, _submitStatus_submitStatusRequest);
//        System.out.println("submitStatus.result=" + _submitStatus__return);
//
//
//        }
//        {
//        System.out.println("Invoking submitSign...");
//        java.lang.String _submitSign_token = "";
//        com.lvmama.vst.order.webservice.contract.ComplementSignRequest _submitSign_complementSignRequest = null;
//        java.lang.String _submitSign__return = port.submitSign(_submitSign_token, _submitSign_complementSignRequest);
//        System.out.println("submitSign.result=" + _submitSign__return);
//
//
//        }
//        {
//        System.out.println("Invoking complementInsurance...");
//        java.lang.String _complementInsurance_token = "";
//        com.lvmama.vst.order.webservice.contract.ComplementInsuranceRequest _complementInsurance_complementInsuranceRequest = null;
//        java.lang.String _complementInsurance__return = port.complementInsurance(_complementInsurance_token, _complementInsurance_complementInsuranceRequest);
//        System.out.println("complementInsurance.result=" + _complementInsurance__return);
//
//
//        }
//        {
//        System.out.println("Invoking getSignCreate...");
//        java.lang.String _getSignCreate_token = "";
//        java.lang.String _getSignCreate_contractid = "";
//        java.lang.String _getSignCreate__return = port.getSignCreate(_getSignCreate_token, _getSignCreate_contractid);
//        System.out.println("getSignCreate.result=" + _getSignCreate__return);
//
//
//        }
//        {
//        System.out.println("Invoking cancelContract...");
//        java.lang.String _cancelContract_token = "";
//        com.lvmama.vst.order.webservice.contract.CancelContractRequest _cancelContract_cancelContractRequest = null;
//        java.lang.String _cancelContract__return = port.cancelContract(_cancelContract_token, _cancelContract_cancelContractRequest);
//        System.out.println("cancelContract.result=" + _cancelContract__return);
//
//
//        }
//        {
//        System.out.println("Invoking getContractUuid...");
//        java.lang.String _getContractUuid_token = "";
//        java.lang.String _getContractUuid_contractno = "";
//        java.lang.String _getContractUuid__return = port.getContractUuid(_getContractUuid_token, _getContractUuid_contractno);
//        System.out.println("getContractUuid.result=" + _getContractUuid__return);
//
//
//        }
//        {
//        System.out.println("Invoking resendMsg...");
//        java.lang.String _resendMsg_token = "";
//        java.lang.String _resendMsg_contractid = "";
//        java.lang.String _resendMsg_guestname = "";
//        java.lang.String _resendMsg_guestmobile = "";
//        java.lang.String _resendMsg__return = port.resendMsg(_resendMsg_token, _resendMsg_contractid, _resendMsg_guestname, _resendMsg_guestmobile);
//        System.out.println("resendMsg.result=" + _resendMsg__return);
//
//
//        }

        System.exit(0);
    }

}
