package com.lvmama.vst.order.webservice.contract;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.4
 * Tue Dec 02 16:01:22 CST 2014
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://server.ws.api.contract.goldpalm.com/", name = "ContractWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface ContractWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "complementGuest", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.ComplementGuest")
    @ResponseWrapper(localName = "complementGuestResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.ComplementGuestResponse")
    @WebMethod
    public java.lang.String complementGuest(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "complementGuestRequest", targetNamespace = "")
        com.lvmama.vst.order.webservice.contract.ComplementGuestRequest complementGuestRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "authentication", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.Authentication")
    @ResponseWrapper(localName = "authenticationResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.AuthenticationResponse")
    @WebMethod
    public java.lang.String authentication(
        @WebParam(name = "code", targetNamespace = "")
        java.lang.String code,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMsgCode", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.GetMsgCode")
    @ResponseWrapper(localName = "getMsgCodeResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.GetMsgCodeResponse")
    @WebMethod
    public java.lang.String getMsgCode(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "contractid", targetNamespace = "")
        java.lang.String contractid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "submitContract", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.SubmitContract")
    @ResponseWrapper(localName = "submitContractResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.SubmitContractResponse")
    @WebMethod
    public java.lang.String submitContract(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "submitContractRequest", targetNamespace = "")
        com.lvmama.vst.order.webservice.contract.SubmitContractRequest submitContractRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "uploadContract", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.UploadContract")
    @ResponseWrapper(localName = "uploadContractResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.UploadContractResponse")
    @WebMethod
    public java.lang.String uploadContract(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "submitContractRequest", targetNamespace = "")
        com.lvmama.vst.order.webservice.contract.SubmitContractRequest submitContractRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "submitStatus", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.SubmitStatus")
    @ResponseWrapper(localName = "submitStatusResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.SubmitStatusResponse")
    @WebMethod
    public java.lang.String submitStatus(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "submitStatusRequest", targetNamespace = "")
        com.lvmama.vst.order.webservice.contract.SubmitStatusRequest submitStatusRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "submitSign", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.SubmitSign")
    @ResponseWrapper(localName = "submitSignResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.SubmitSignResponse")
    @WebMethod
    public java.lang.String submitSign(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "complementSignRequest", targetNamespace = "")
        com.lvmama.vst.order.webservice.contract.ComplementSignRequest complementSignRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "complementInsurance", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.ComplementInsurance")
    @ResponseWrapper(localName = "complementInsuranceResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.ComplementInsuranceResponse")
    @WebMethod
    public java.lang.String complementInsurance(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "complementInsuranceRequest", targetNamespace = "")
        com.lvmama.vst.order.webservice.contract.ComplementInsuranceRequest complementInsuranceRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSignCreate", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.GetSignCreate")
    @ResponseWrapper(localName = "getSignCreateResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.GetSignCreateResponse")
    @WebMethod
    public java.lang.String getSignCreate(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "contractid", targetNamespace = "")
        java.lang.String contractid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cancelContract", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.CancelContract")
    @ResponseWrapper(localName = "cancelContractResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.CancelContractResponse")
    @WebMethod
    public java.lang.String cancelContract(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "cancelContractRequest", targetNamespace = "")
        com.lvmama.vst.order.webservice.contract.CancelContractRequest cancelContractRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getContractUuid", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.GetContractUuid")
    @ResponseWrapper(localName = "getContractUuidResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.GetContractUuidResponse")
    @WebMethod
    public java.lang.String getContractUuid(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "contractno", targetNamespace = "")
        java.lang.String contractno
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "resendMsg", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.ResendMsg")
    @ResponseWrapper(localName = "resendMsgResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.lvmama.vst.order.webservice.contract.ResendMsgResponse")
    @WebMethod
    public java.lang.String resendMsg(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "contractid", targetNamespace = "")
        java.lang.String contractid,
        @WebParam(name = "guestname", targetNamespace = "")
        java.lang.String guestname,
        @WebParam(name = "guestmobile", targetNamespace = "")
        java.lang.String guestmobile
    );
}
