
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.lvmama.vst.order.webservice.contract;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.1.4
 * Tue Dec 02 16:01:22 CST 2014
 * Generated source version: 2.1.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "ContractWebService",
                      portName = "ContractWebServicePort",
                      targetNamespace = "http://www.springframework.org/schema/beans",
                      wsdlLocation = "http://test.contract-api.palmyou.com/ntsms-contract-api/service/ContractWebService?wsdl",
                      endpointInterface = "com.lvmama.vst.order.webservice.contract.ContractWebService")
                      
public class ContractWebServiceImpl implements ContractWebService {

	private static final Logger logger = LoggerFactory.getLogger(ContractWebServiceImpl.class);
    /* (non-Javadoc)
     * @see com.lvmama.vst.order.webservice.contract.ContractWebService#complementGuest(java.lang.String  token ,)com.lvmama.vst.order.webservice.contract.ComplementGuestRequest  complementGuestRequest )*
     */
    public java.lang.String complementGuest(java.lang.String token,com.lvmama.vst.order.webservice.contract.ComplementGuestRequest complementGuestRequest) { 
        logger.info("Executing operation complementGuest");
        System.out.println(token);
        System.out.println(complementGuestRequest);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
        	logger.error("{}", ex);
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lvmama.vst.order.webservice.contract.ContractWebService#authentication(java.lang.String  code ,)java.lang.String  password )*
     */
    public java.lang.String authentication(java.lang.String code,java.lang.String password) { 
        logger.info("Executing operation authentication");
        System.out.println(code);
        System.out.println(password);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            logger.error("{}", ex);
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lvmama.vst.order.webservice.contract.ContractWebService#getMsgCode(java.lang.String  token ,)java.lang.String  contractid )*
     */
    public java.lang.String getMsgCode(java.lang.String token,java.lang.String contractid) { 
        logger.info("Executing operation getMsgCode");
        System.out.println(token);
        System.out.println(contractid);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            logger.error("{}", ex);
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lvmama.vst.order.webservice.contract.ContractWebService#submitContract(java.lang.String  token ,)com.lvmama.vst.order.webservice.contract.SubmitContractRequest  submitContractRequest )*
     */
    public java.lang.String submitContract(java.lang.String token,com.lvmama.vst.order.webservice.contract.SubmitContractRequest submitContractRequest) { 
        logger.info("Executing operation submitContract");
        System.out.println(token);
        System.out.println(submitContractRequest);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            logger.error("{}", ex);
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lvmama.vst.order.webservice.contract.ContractWebService#uploadContract(java.lang.String  token ,)com.lvmama.vst.order.webservice.contract.SubmitContractRequest  submitContractRequest )*
     */
    public java.lang.String uploadContract(java.lang.String token,com.lvmama.vst.order.webservice.contract.SubmitContractRequest submitContractRequest) { 
        logger.info("Executing operation uploadContract");
        System.out.println(token);
        System.out.println(submitContractRequest);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            logger.error("{}", ex);
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lvmama.vst.order.webservice.contract.ContractWebService#submitStatus(java.lang.String  token ,)com.lvmama.vst.order.webservice.contract.SubmitStatusRequest  submitStatusRequest )*
     */
    public java.lang.String submitStatus(java.lang.String token,com.lvmama.vst.order.webservice.contract.SubmitStatusRequest submitStatusRequest) { 
        logger.info("Executing operation submitStatus");
        System.out.println(token);
        System.out.println(submitStatusRequest);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            logger.error("{}", ex);
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lvmama.vst.order.webservice.contract.ContractWebService#submitSign(java.lang.String  token ,)com.lvmama.vst.order.webservice.contract.ComplementSignRequest  complementSignRequest )*
     */
    public java.lang.String submitSign(java.lang.String token,com.lvmama.vst.order.webservice.contract.ComplementSignRequest complementSignRequest) { 
        logger.info("Executing operation submitSign");
        System.out.println(token);
        System.out.println(complementSignRequest);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            logger.error("{}", ex);
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lvmama.vst.order.webservice.contract.ContractWebService#complementInsurance(java.lang.String  token ,)com.lvmama.vst.order.webservice.contract.ComplementInsuranceRequest  complementInsuranceRequest )*
     */
    public java.lang.String complementInsurance(java.lang.String token,com.lvmama.vst.order.webservice.contract.ComplementInsuranceRequest complementInsuranceRequest) { 
        logger.info("Executing operation complementInsurance");
        System.out.println(token);
        System.out.println(complementInsuranceRequest);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            logger.error("{}", ex);
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lvmama.vst.order.webservice.contract.ContractWebService#getSignCreate(java.lang.String  token ,)java.lang.String  contractid )*
     */
    public java.lang.String getSignCreate(java.lang.String token,java.lang.String contractid) { 
        logger.info("Executing operation getSignCreate");
        System.out.println(token);
        System.out.println(contractid);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            logger.error("{}", ex);
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lvmama.vst.order.webservice.contract.ContractWebService#cancelContract(java.lang.String  token ,)com.lvmama.vst.order.webservice.contract.CancelContractRequest  cancelContractRequest )*
     */
    public java.lang.String cancelContract(java.lang.String token,com.lvmama.vst.order.webservice.contract.CancelContractRequest cancelContractRequest) { 
        logger.info("Executing operation cancelContract");
        System.out.println(token);
        System.out.println(cancelContractRequest);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            logger.error("{}", ex);
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lvmama.vst.order.webservice.contract.ContractWebService#getContractUuid(java.lang.String  token ,)java.lang.String  contractno )*
     */
    public java.lang.String getContractUuid(java.lang.String token,java.lang.String contractno) { 
        logger.info("Executing operation getContractUuid");
        System.out.println(token);
        System.out.println(contractno);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            logger.error("{}", ex);
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lvmama.vst.order.webservice.contract.ContractWebService#resendMsg(java.lang.String  token ,)java.lang.String  contractid ,)java.lang.String  guestname ,)java.lang.String  guestmobile )*
     */
    public java.lang.String resendMsg(java.lang.String token,java.lang.String contractid,java.lang.String guestname,java.lang.String guestmobile) { 
        logger.info("Executing operation resendMsg");
        System.out.println(token);
        System.out.println(contractid);
        System.out.println(guestname);
        System.out.println(guestmobile);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            logger.error("{}", ex);
            throw new RuntimeException(ex);
        }
    }

}
