package com.lvmama.vst.order.builder;

import com.lvmama.vst.back.order.po.OrderEnum;

/**
 * 综合查询常量配置类
 * 
 * @author wenzhengtao
 * 
 */
public interface IComplexQuerySQLConstant {
	// 订单表
	String T_ORD_ORDER = "ORD_ORDER";
	// 订单子项
	String T_ORD_ORDER_ITEM = "ORD_ORDER_ITEM";
	// 订单子项
	String T_ORD_RESPONSIBLE = "ORD_RESPONSIBLE";	
	// 酒店各天情况
	String T_ORD_ORDER_HOTEL_TIME_RATE = "ORD_ORDER_HOTEL_TIME_RATE";
	// 订单金额变换信息
	String T_ORD_ORDER_AMOUNT_ITEM = "ORD_ORDER_AMOUNT_ITEM";
	// 地址信息
	String T_ORD_ADDRESS = "ORD_ADDRESS";
	// 人员信息
	String T_ORD_PERSON = "ORD_PERSON";
	// 担保信息
	String T_ORD_GUARANTEE_CREDIT_CARD = "ORD_GUARANTEE_CREDIT_CARD";
	// 订单打包信息
	String T_ORD_ORDER_PACK = "ORD_ORDER_PACK";
	// 订单库存信息
	String T_ORD_ORDER_STOCK = "ORD_ORDER_STOCK";
	
	
	// 订单附加状态表
	String T_ORD_ADDITION_STATUS = "ORD_ADDITION_STATUS";
	
	// 订单订单合同表
	String T_ORD_TRAVEL_CONTRACT = "ORD_TRAVEL_CONTRACT";
			
	// 快递寄件清单表
	String T_ORD_COURIER_LISTING = "ORD_COURIER_LISTING";	
	
	//订单活动表
	String T_COM_AUDIT = "COM_AUDIT";
	
	//O2O门店系统 O2O订单表
	String T_O2O_ORDER = "O2O_ORDER";
	//O2O门店系统 O2O订单佣金表
	String T_ORD_ORDER_COMMISSION = "ORD_ORDER_COMMISSION";
	
	// SELECT关键字
	String K_SELECT = " SELECT ";
	// FROM关键字
	String K_FROM = " FROM ";
	// WHERE关键字
	String K_WHERE = " WHERE ";
	// AND关键字
	String K_AND = " AND ";
	// OR关键字
	String K_OR = " OR ";
	// ORDER BY关键字
	String K_ORDER_BY = " ORDER BY ";
	// GROUP BY关键字
	String K_GROUP_BY = " GROUP BY ";
	// HAVING关键字
	String K_HAVING = " HAVING ";
	// COMMA关键字
	String K_COMMA = " , ";
	// 左括号关键字
	String K_LEFT_PARENTHESIS = " ( ";
	// 右括号关键字
	String K_RIGHT_PARENTHESIS = " ) ";
	// 分页语句切分常量
	String C_PAGE_SQL_1 = " SELECT * FROM (SELECT T.*, ROWNUM AS ROWNUM1 FROM ( ";
	String C_PAGE_SQL_2 = " ) T WHERE ROWNUM <=";
	String C_PAGE_SQL_3 = " ) WHERE ROWNUM1 >=";
	// 订单关联查询结束SQL
	String C_END_SQL = " )) ";
	//订单子项关联查询结束SQL
	String C_END_SQL_1 = " )))) ";
	// 查询订单子项SQL
	String C_ORD_ORDER_ITEM_SQL = "SELECT DISTINCT ORD_ORDER_ITEM.* FROM ORD_ORDER_ITEM WHERE ORDER_ID IN (SELECT ORDER_ID FROM (";
	// 查询订单游客SQL
	String C_ORD_PERSON_SQL = "SELECT DISTINCT ORD_PERSON.* FROM ORD_PERSON WHERE ORD_PERSON.OBJECT_TYPE = '" + OrderEnum.ORDER_PERSON_OBJECT_TYPE.ORDER.toString()+"' AND ORD_PERSON.OBJECT_ID IN (SELECT ORDER_ID FROM (";
	// 查询订单快递地址SQL
	String C_ORD_ADDRESS_SQL = "SELECT DISTINCT ORD_ADDRESS.* FROM ORD_ADDRESS WHERE ORD_ADDRESS.ORD_PERSON_ID IN (SELECT ORD_PERSON_ID FROM  (SELECT ORD_PERSON.* FROM ORD_PERSON WHERE OBJECT_TYPE='ORDER' AND OBJECT_ID IN (SELECT ORDER_ID FROM (";
		
	//查询订单打包SQL
	String C_ORD_ORDER_PACK_SQL = "SELECT DISTINCT ORD_ORDER_PACK.* FROM ORD_ORDER_PACK WHERE ORDER_ID IN (SELECT ORDER_ID FROM (";
	//查询订单金额SQL
	String C_ORD_ORDER_AMOUNT_ITEM_SQL = "SELECT DISTINCT ORD_ORDER_AMOUNT_ITEM.* FROM ORD_ORDER_AMOUNT_ITEM WHERE ORDER_ID IN (SELECT ORDER_ID FROM (";
	//查询订单担保SQL
	String C_ORD_GUARANTEE_CREDIT_CARD_SQL = "SELECT DISTINCT ORD_GUARANTEE_CREDIT_CARD.* FROM ORD_GUARANTEE_CREDIT_CARD WHERE ORDER_ID IN (SELECT ORDER_ID FROM (";
	//查询订单酒店SQL
	String C_ORD_ORDER_HOTEL_TIME_RATE_SQL = "SELECT DISTINCT ORD_ORDER_HOTEL_TIME_RATE.* FROM ORD_ORDER_HOTEL_TIME_RATE WHERE ORDER_ITEM_ID IN ( SELECT ORDER_ITEM_ID FROM (SELECT DISTINCT ORD_ORDER_ITEM.* FROM ORD_ORDER_ITEM WHERE ORDER_ID IN (SELECT ORDER_ID FROM (";
	//查询订单库存SQL
	String C_ORD_ORDER_STOCK_SQL = "SELECT DISTINCT ORD_ORDER_STOCK.* FROM ORD_ORDER_STOCK WHERE ORDER_ITEM_ID IN ( SELECT ORDER_ITEM_ID FROM (SELECT DISTINCT ORD_ORDER_ITEM.* FROM ORD_ORDER_ITEM WHERE ORDER_ID IN (SELECT ORDER_ID FROM (";
	
	// 查询订单附加状态SQL
	String C_ORD_ADDITION_STATUS_SQL = "SELECT DISTINCT ORD_ADDITION_STATUS.* FROM ORD_ADDITION_STATUS WHERE ORD_ADDITION_STATUS.ORDER_ID IN (SELECT ORDER_ID FROM (";
	
	// 查询订单合同SQL
	String C_ORD_TRAVEL_CONTRACT_SQL = "SELECT DISTINCT ORD_TRAVEL_CONTRACT.* FROM ORD_TRAVEL_CONTRACT WHERE ORD_TRAVEL_CONTRACT.ORDER_ID IN (SELECT ORDER_ID FROM (";
	
	// 查询快递寄件清单SQL
	String C_ORD_COURIER_LISTING_SQL = "SELECT DISTINCT ORD_COURIER_LISTING.* FROM ORD_COURIER_LISTING WHERE ORD_COURIER_LISTING.ORDER_ID IN (SELECT ORDER_ID FROM  (";
	
	//查询ORD_FORM_INFO关联数据
	String C_ORD_FORM_INFO_SQL = "SELECT DISTINCT ORD_FORM_INFO.* FROM ORD_FORM_INFO WHERE ORDER_ID IN (SELECT ORDER_ID FROM (";
}
